name: 'Update schedule'

on:
  schedule:
  - cron: '40 16 * * *'  # 北京时间00:40 (UTC+8)
  - cron: '15 2 * * *'   # 北京时间10:15 (UTC+8)
  - cron: '0 7 * * *'    # 北京时间15:00 (UTC+8)
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  push:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 240
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest' ]
    steps:
      - uses: actions/checkout@v3
      - name: Run with setup-python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          update-environment: true
          cache: 'pipenv'
      - name: Install pipenv
        run: pip3 install --user pipenv
      - name: Install dependecies
        run: |
          pipenv lock
          pipenv --python 3.13 && pipenv install --deploy
      - name: Update EPG
        run: pipenv run epg
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [[ -f "output/epg.xml" ]]; then
            git add -f "output/epg.xml"
          fi
          if [[ -f "output/epg.gz" ]]; then
            git add -f "output/epg.gz"
          fi
          if ! git diff --staged --quiet; then
            git commit -m "Github Action Auto Updated"
            git push --force
          fi
      
